In [26]:
import sqlite3
import requests
from bs4 import BeautifulSoup
import pandas as pd

# 2024 WWW Accepted Papers

In [40]:

def create_database(DB_PATH):
    """Create the database and the Conference table."""
    conn = sqlite3.connect(DB_PATH)
    cursor = conn.cursor()

    cursor.execute('''
    CREATE TABLE IF NOT EXISTS Conference (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        Title TEXT NOT NULL,
        Author TEXT NOT NULL,
        PDF_Link TEXT,
        Code_URL TEXT,
        Conference_Name TEXT NOT NULL
    )
    ''')

    print("Conference 테이블이 생성되었습니다.")
    conn.commit()
    conn.close()

def save_to_database(df, conference_name, DB_PATH):
    conn = sqlite3.connect(DB_PATH, timeout=10)
    cursor = conn.cursor()

    try:
        for _, row in df.iterrows():  # ✅ iterrows() 사용하여 DataFrame의 각 행을 처리
            # 중복 데이터 확인
            cursor.execute('''
            SELECT 1 FROM Conference WHERE Title = ? AND Author = ? AND Conference_Name = ?
            ''', (row['title'], row['authors'], conference_name))
            result = cursor.fetchone()

            if not result:
                cursor.execute('''
                INSERT INTO Conference (Title, Author, PDF_Link, Code_URL, Conference_Name)
                VALUES (?, ?, ?, ?, ?)
                ''', (row['title'], row['authors'], row['pdf_link'], row['code_url'], conference_name))

        conn.commit()
        print(f"{len(df)}개의 논문이 {conference_name}에 저장되었습니다.")
    except sqlite3.Error as e:
        print(f"Database error: {e}")
    finally:
        conn.close()


def get_www_papers(page_link, conference_name):
    """WWW 2024 학회의 Accepted Papers 페이지에서 논문 정보 크롤링"""
    page_content = requests.get(page_link)
    
    if page_content is None:
        return []

    soup = BeautifulSoup(page_content.text, "html.parser")

    # HTML을 저장 (디버깅용)
    with open("www2024_accepted_papers.html", "w", encoding="utf-8") as f:
        f.write(soup.prettify())

    papers = []

    # 논문 리스트가 포함된 div 태그 찾기
    for card in soup.find_all("div", class_="card my-2 p-2"):
        title_tag = card.find("strong")
        author_tag = card.find("p", class_="m-0 p-0")
        pdf_link_tag = card.find("a", class_="btn btn-sm bg-primary my-1")
        code_url_tag = card.find("a", text="GitHub")  # GitHub 링크가 있을 경우

        title = title_tag.text.strip() if title_tag else None
        authors = author_tag.text.strip() if author_tag else None
        pdf_link = pdf_link_tag["href"] if pdf_link_tag else None
        code_url = code_url_tag["href"] if code_url_tag else None
        
        papers.append({"title": title, "authors": authors, "pdf_link": None, "code_url": pdf_link, 'conference_name': conference_name})

    return papers

In [30]:
page_link='https://www2024.thewebconf.org/accepted/research-tracks/' 
DB_PATH = "www_conference_2024.db"
conference_name = 'WWW 2024'
papers = get_www_papers(page_link, conference_name)

/tmp/ipykernel_2099291/2277661230.py:66: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  code_url_tag = card.find("a", text="GitHub")  # GitHub 링크가 있을 경우

In [31]:
response = requests.get(page_link) 
if response.status_code == 200:
    soup = BeautifulSoup(response.text, 'html.parser') 
    with open('www2024_accepted_papers.html', 'w', encoding='utf-8') as f:
        f.write(soup.prettify())

In [34]:
import pandas as pd 


df_papers = pd.DataFrame(papers) 
df_papers.head()

,title,authors,pdf_link,code_url,conference_name
0,Intelligent Model Update Strategy for Sequenti...,"Zheqi Lv, Wenqiao Zhang, Zhengyu Chen, Shengyu...",None,None,WWW 2024
1,Advancing Web 3.0: Making Smart Contracts Smar...,"Junqin Huang, Linghe Kong, Guanjie Cheng, Qiao...",None,https://doi.org/10.5281/zenodo.10566861,WWW 2024
2,Efficient Computation of Signature-Restricted ...,Yizheng Zhao,None,None,WWW 2024
3,From Promises to Practice: Evaluating the Priv...,"Xiaoyin Liu, Wenzhi Li, Qinsheng Hou, Shishuai...",None,https://doi.org/10.5281/zenodo.10577793,WWW 2024
4,"LFDe: A Lighter, Faster and More Data-Efficien...","Zhigang Kan, Liwen Peng, Yifu Gao, Ning Liu, L...",None,None,WWW 2024

In [37]:
# DB 생성 
DB_PATH = "www_conference_2024.db" 
create_database(DB_PATH)

Conference 테이블이 생성되었습니다.

In [41]:
save_to_database(df_papers, conference_name, DB_PATH)

405개의 논문이 WWW 2024에 저장되었습니다.

# 2023 WWW Accepted Papers

In [60]:
url="https://www.sigweb.org/toc/www23.html"
DB_PATH = 'www_conference_2023.db' 
create_database(DB_PATH)

Conference 테이블이 생성되었습니다.

In [61]:
def get_www_papers(page_link, conference_name):
    """WWW 2023 학회의 Accepted Papers 페이지에서 논문 정보 크롤링"""
    
    # 웹페이지 요청
    response = requests.get(page_link)
    
    if response.status_code != 200:
        print("❌ 페이지를 불러오지 못했습니다.")
        return []

    soup = BeautifulSoup(response.text, "html.parser")

    # HTML을 저장 (디버깅용)
    with open("www2023_accepted_papers.html", "w", encoding="utf-8") as f:
        f.write(soup.prettify())

    papers = []

    # 논문 제목과 저자 정보 추출
    for paper_section in soup.find_all("h3"):  # 논문 제목이 포함된 태그 찾기
        title_tag = paper_section.find("a")  # 제목이 포함된 a 태그 찾기
        author_list = paper_section.find_next_sibling("ul")  # 저자 목록이 포함된 ul 태그 찾기

        if title_tag and author_list:
            title_text = title_tag.text.strip()  # 제목 텍스트 추출
            authors = [li.text.strip() for li in author_list.find_all("li")]  # 저자 목록 추출
            author_text = ", ".join(authors)  # 저자 이름을 쉼표로 구분

            papers.append({
                "title": title_text,
                "authors": author_text,
                "pdf_link": None,
                "code_url": None,
                "conference_name": conference_name
            })

    return papers

In [57]:
papers = get_www_papers(url, 'WWW 2023')

[{'title': 'Using diversity as a source of scientific innovation for the Web', 'authors': 'Barbara Poblete', 'pdf_link': None, 'code_url': None, 'conference_name': 'WWW 2023'}, {'title': 'Decolonizing Creative Labor in the age of AI', 'authors': 'Payal Arora', 'pdf_link': None, 'code_url': None, 'conference_name': 'WWW 2023'}, {'title': 'Concept Regulation in the Social Sciences', 'authors': 'Zachary Elkins', 'pdf_link': None, 'code_url': None, 'conference_name': 'WWW 2023'}, {'title': 'GNNs and Graph Generative models for biomedical applications', 'authors': 'Michalis Vazirgiannis', 'pdf_link': None, 'code_url': None, 'conference_name': 'WWW 2023'}, {'title': 'CONNECTIVITY', 'authors': 'Robert Melancton Metcalfe', 'pdf_link': None, 'code_url': None, 'conference_name': 'WWW 2023'}, {'title': 'GELTOR: A Graph Embedding Method based on Listwise Learning to Rank', 'authors': 'Masoud Reyhani Hamedani, Jin-Su Ryu, Sang-Wook Kim', 'pdf_link': None, 'code_url': None, 'conference_name': 'WWW 2023'}, {'title': 'Graph-less Collaborative Filtering', 'authors': 'Lianghao Xia, Chao Huang, Jiao Shi, Yong Xu', 'pdf_link': None, 'code_url': None, 'conference_name': 'WWW 2023'}, {'title': 'Fair Graph Representation Learning via Diverse Mixture-of-Experts', 'authors': 'Zheyuan Liu, Chunhui Zhang, Yijun Tian, Erchi Zhang, Chao Huang, Yanfang Ye, Chuxu Zhang', 'pdf_link': None, 'code_url': None, 'conference_name': 'WWW 2023'}, {'title': 'Multi-Aspect Heterogeneous Graph Augmentation', 'authors': 'Yuchen Zhou, Yanan Cao, Yongchao Liu, Yanmin Shang, Peng Zhang, Zheng Lin, Yun Yue, Baokun Wang, Xing Fu, Weiqiang Wang', 'pdf_link': None, 'code_url': None, 'conference_name': 'WWW 2023'}, {'title': 'Testing Cluster Properties of Signed Graphs', 'authors': 'Florian Adriaens, Simon Apers', 'pdf_link': None, 'code_url': None, 'conference_name': 'WWW 2023'}, {'title': 'RSGNN: A Model-agnostic Approach for Enhancing the Robustness of Signed Graph Neural Networks', 'authors': 'Zeyu Zhang, Jiamou Liu, Xianda Zheng, Yifei Wang, Pengqian Han, Yupan Wang, Kaiqi Zhao, Zijian Zhang', 'pdf_link': None, 'code_url': None, 'conference_name': 'WWW 2023'}, {'title': 'NeuKron: Constant-Size Lossy Compression of Sparse Reorderable Matrices and Tensors', 'authors': 'Taehyung Kwon, Jihoon Ko, Jinhong Jung, Kijung Shin', 'pdf_link': None, 'code_url': None, 'conference_name': 'WWW 2023'}, {'title': 'Multi-aspect Diffusion Network Inference', 'authors': 'Hao Huang, Keqi Han, Beicheng Xu, Ting Gan', 'pdf_link': None, 'code_url': None, 'conference_name': 'WWW 2023'}, {'title': 'Collaboration-Aware Graph Convolutional Network for Recommender Systems', 'authors': 'Yu Wang, Yuying Zhao, Yi Zhang, Tyler Derr', 'pdf_link': None, 'code_url': None, 'conference_name': 'WWW 2023'}, {'title': 'Pairwise-interactions-based Bayesian Inference of Network Structure from Information Cascades', 'authors': 'Chao Gao, Yuchen Wang, Zhen Wang, Xianghua Li, Xuelong Li', 'pdf_link': None, 'code_url': None, 'conference_name': 'WWW 2023'}, {'title': 'Encoding Node Diffusion Competence and Role Significance for Network Dismantling', 'authors': 'Jiazheng Zhang, Bang Wang', 'pdf_link': None, 'code_url': None, 'conference_name': 'WWW 2023'}, {'title': 'Hierarchical Knowledge Graph Learning Enabled Socioeconomic Indicator Prediction in Location-Based Social Network', 'authors': 'Zhilun Zhou, Yu Liu, Jingtao Ding, Depeng Jin, Yong Li', 'pdf_link': None, 'code_url': None, 'conference_name': 'WWW 2023'}, {'title': 'Opinion Maximization in Social Networks via Leader Selection', 'authors': 'Xiaotian Zhou, Zhongzhi Zhang', 'pdf_link': None, 'code_url': None, 'conference_name': 'WWW 2023'}, {'title': 'SeeGera: Self-supervised Semi-implicit Graph Variational Auto-encoders with Masking', 'authors': 'Xiang Li, Tiandi Ye, Caihua Shan, Dongsheng Li, Ming Gao', 'pdf_link': None, 'code_url': None, 'conference_name': 'WWW 2023'}, {'title': 'Graph Self-supervised Learning with Augmentation-aware Contrastive Learning', 'authors': 'Dong Chen, Xiang Zhao, Wei Wang, Zhen Tan, Weidong Xiao', 'pdf_link': None, 'code_url': None, 'conference_name': 'WWW 2023'}, {'title': 'Enhancing Hierarchy-Aware Graph Networks with Deep Dual Clustering for Session-based Recommendation', 'authors': 'Jiajie Su, Chaochao Chen, Weiming Liu, Fei Wu, Xiaolin Zheng, Haoming Lyu', 'pdf_link': None, 'code_url': None, 'conference_name': 'WWW 2023'}, {'title': 'Unifying and Improving Graph Convolutional Neural Networks with Wavelet Denoising Filters', 'authors': 'Liangtian Wan, Xiaona Li, Huijin Han, Xiaoran Yan, Lu Sun, Zhaolong Ning, Feng Xia', 'pdf_link': None, 'code_url': None, 'conference_name': 'WWW 2023'}, {'title': 'HyConvE: A Novel Embedding Model for Knowledge Hypergraph Link Prediction with Convolutional Neural Networks', 'authors': 'Chenxu Wang, Xin Wang, Zhao Li, Zirui Chen, Jianxin Li', 'pdf_link': None, 'code_url': None, 'conference_name': 'WWW 2023'}, {'title': 'Efficient Approximation Algorithms for the Diameter-Bounded Max-Coverage Group Steiner Tree Problem', 'authors': 'Ke Zhang, Xiaoqing Wang, Gong Cheng', 'pdf_link': None, 'code_url': None, 'conference_name': 'WWW 2023'}, {'title': 'Neighborhood Structure Configuration Models', 'authors': 'Felix I. Stamm, Michael Scholkemper, Markus Strohmaier, Michael T. Schaub', 'pdf_link': None, 'code_url': None, 'conference_name': 'WWW 2023'}, {'title': 'CurvDrop: A Ricci Curvature Based Approach to Prevent Graph Neural Networks from Over-Smoothing and Over-Squashing', 'authors': 'Yang Liu, Chuan Zhou, Shirui Pan, Jia Wu, Zhao Li, Hongyang Chen, Peng Zhang', 'pdf_link': None, 'code_url': None, 'conference_name': 'WWW 2023'}, {'title': 'Disentangling Degree-related Biases and Interest for Out-of-Distribution Generalized Directed Network Embedding', 'authors': 'Hyunsik Yoo, Yeon-Chang Lee, Kijung Shin, Sang-Wook Kim', 'pdf_link': None, 'code_url': None, 'conference_name': 'WWW 2023'}, {'title': 'ConsRec: Learning Consensus Behind Interactions for Group Recommendation', 'authors': 'Xixi Wu, Yun Xiong, Yao Zhang, Yizhu Jiao, Jiawei Zhang, Yangyong Zhu, Philip S. Yu', 'pdf_link': None, 'code_url': None, 'conference_name': 'WWW 2023'}, {'title': 'A Post-Training Framework for Improving Heterogeneous Graph Neural Networks', 'authors': 'Cheng Yang, Xumeng Gong, Chuan Shi, Philip Yu', 'pdf_link': None, 'code_url': None, 'conference_name': 'WWW 2023'}, {'title': 'Link Prediction on Latent Heterogeneous Graphs', 'authors': 'Trung-Kien Nguyen, Zemin Liu, Yuan Fang', 'pdf_link': None, 'code_url': None, 'conference_name': 'WWW 2023'}, {'title': 'Predicting the Silent Majority on Graphs: Knowledge Transferable Graph Neural Network', 'authors': 'Wendong Bi, Bingbing Xu, Xiaoqian Sun, Li Xu, Huawei Shen, Xueqi Cheng', 'pdf_link': None, 'code_url': None, 'conference_name': 'WWW 2023'}, {'title': 'Lightweight source localization for large-scale social networks', 'authors': 'Zhen Wang, Dongpeng Hou, Chao Gao, Xiaoyu Li, Xuelong Li', 'pdf_link': None, 'code_url': None, 'conference_name': 'WWW 2023'}, {'title': 'Automated Spatio-Temporal Graph Contrastive Learning', 'authors': 'Qianru Zhang, Chao Huang, Lianghao Xia, Zheng Wang, Zhonghang Li, Siuming Yiu', 'pdf_link': None, 'code_url': None, 'conference_name': 'WWW 2023'}, {'title': 'Graph Neural Networks with Diverse Spectral Filtering', 'authors': 'Jingwei Guo, Kaizhu Huang, Xinping Yi, Rui Zhang', 'pdf_link': None, 'code_url': None, 'conference_name': 'WWW 2023'}, {'title': 'Characterization of Simplicial Complexes by Counting Simplets Beyond Four Nodes', 'authors': 'Hyunju Kim, Jihoon Ko, Fanchen Bu, Kijung Shin', 'pdf_link': None, 'code_url': None, 'conference_name': 'WWW 2023'}, {'title': 'Robust Mid-Pass Filtering Graph Convolutional Networks', 'authors': 'Jincheng Huang, Lun Du, Xu Chen, Qiang Fu, Shi Han, Dongmei Zhang', 'pdf_link': None, 'code_url': None, 'conference_name': 'WWW 2023'}, {'title': 'Semi-decentralized Federated Ego Graph Learning for Recommendation', 'authors': 'Liang Qu, Ningzhi Tang, Ruiqi Zheng, Quoc Viet Hung Nguyen, Zi Huang, Yuhui Shi, Hongzhi Yin', 'pdf_link': None, 'code_url': None, 'conference_name': 'WWW 2023'}, {'title': 'xGCN: An Extreme Graph Convolutional Network for Large-scale Social Link Prediction', 'authors': 'Xiran Song, Jianxun Lian, Hong Huang, Zihan Luo, Wei Zhou, Xue Lin, Mingqi Wu, Chaozhuo Li, Xing Xie, Hai Jin', 'pdf_link': None, 'code_url': None, 'conference_name': 'WWW 2023'}, {'title': 'SINCERE: Sequential Interaction Networks representation learning on Co-Evolving RiEmannian manifolds', 'authors': 'Junda Ye, Zhongbao Zhang, Li Sun, Yang Yan, Feiyang Wang, Fuxin Ren', 'pdf_link': None, 'code_url': None, 'conference_name': 'WWW 2023'}, {'title': 'PARROT: Position-Aware Regularized Optimal Transport for Network Alignment', 'authors': 'Zhichen Zeng, Si Zhang, Yinglong Xia, Hanghang Tong', 'pdf_link': None, 'code_url': None, 'conference_name': 'WWW 2023'}, {'title': 'Joint Internal Multi-Interest Exploration and External Domain Alignment for Cross Domain Sequential Recommendation', 'authors': 'Weiming Liu, Xiaolin Zheng, Chaochao Chen, Jiajie Su, Xinting Liao, Mengling Hu, Yanchao Tan', 'pdf_link': None, 'code_url': None, 'conference_name': 'WWW 2023'}, {'title': 'Graph Neural Network with Two Uplift Estimators for Label-Scarcity Individual Uplift Modeling', 'authors': 'Dingyuan Zhu, Daixin Wang, Zhiqiang Zhang, Kun Kuang, Yan Zhang, Yulin Kang, Jun Zhou', 'pdf_link': None, 'code_url': None, 'conference_name': 'WWW 2023'}, {'title': 'Label Information Enhanced Fraud Detection against Low Homophily in Graphs', 'authors': 'Yuchen Wang, Jinghui Zhang, Zhengjie Huang, Weibin Li, Shikun Feng, Ziheng Ma, Yu Sun, Dianhai Yu, Fang Dong, Jiahui Jin, Beilun Wang, Junzhou Luo', 'pdf_link': None, 'code_url': None, 'conference_name': 'WWW 2023'}, {'title': 'GraphPrompt: Unifying Pre-Training and Downstream Tasks for Graph Neural Networks', 'authors': 'Zemin Liu, Xingtong Yu, Yuan Fang, Xinming Zhang', 'pdf_link': None, 'code_url': None, 'conference_name': 'WWW 2023'}, {'title': 'An Attentional Multi-scale Co-evolving Model for Dynamic Link Prediction', 'authors': 'Guozhen Zhang, Tian Ye, Depeng Jin, Yong Li', 'pdf_link': None, 'code_url': None, 'conference_name': 'WWW 2023'}, {'title': 'Robust Graph Representation Learning for Local Corruption Recovery', 'authors': 'Bingxin Zhou, Yuanhong Jiang, Yuguang Wang, Jingwei Liang, Junbin Gao, Shirui Pan, Xiaoqun Zhang', 'pdf_link': None, 'code_url': None, 'conference_name': 'WWW 2023'}, {'title': 'Intra and Inter Domain HyperGraph Convolutional Network for Cross-Domain Recommendation', 'authors': 'Zhongxuan Han, Xiaolin Zheng, Chaochao Chen, Wenjie Cheng, Yang Yao', 'pdf_link': None, 'code_url': None, 'conference_name': 'WWW 2023'}, {'title': 'Hyperbolic Geometric Graph Representation Learning for Hierarchy-imbalance Node Classification', 'authors': 'Xingcheng Fu, Yuecen Wei, Qingyun Sun, Haonan Yuan, Jia Wu, Hao Peng, Jianxin Li', 'pdf_link': None, 'code_url': None, 'conference_name': 'WWW 2023'}, {'title': 'Graph Neural Networks without Propagation', 'authors': 'Liang Yang, Qiuliang Zhang, Runjie Shi, Wenmiao Zhou, Bingxin Niu, Chuan Wang, Xiaochun Cao, Dongxiao He, Zhen Wang, Yuanfang Guo', 'pdf_link': None, 'code_url': None, 'conference_name': 'WWW 2023'}, {'title': 'TIGER: Temporal Interaction Graph Embedding with Restarts', 'authors': 'Yao Zhang, Yun Xiong, Yongxiang Liao, Yiheng Sun, Yucheng Jin, Xuehao Zheng, Yangyong Zhu', 'pdf_link': None, 'code_url': None, 'conference_name': 'WWW 2023'}, {'title': 'Self-Supervised Teaching and Learning of Representations on Graphs', 'authors': 'Liangtian Wan, Zhenqiang Fu, Lu Sun, Xianpeng Wang, Gang Xu, Xiaoran Yan, Feng Xia', 'pdf_link': None, 'code_url': None, 'conference_name': 'WWW 2023'}, {'title': 'SE-GSL: A General and Effective Graph Structure Learning Framework through Structural Entropy Optimization', 'authors': 'Dongcheng Zou, Hao Peng, Xiang Huang, Renyu Yang, Jianxin Li, Jia Wu, Chunyang Liu, Philip S. Yu', 'pdf_link': None, 'code_url': None, 'conference_name': 'WWW 2023'}, {'title': 'Homophily-oriented Heterogeneous Graph Rewiring', 'authors': 'Jiayan Guo, Lun Du, Wendong Bi, Qiang Fu, Xiaojun Ma, Xu Chen, Shi Han, Dongmei Zhang, Yan Zhang', 'pdf_link': None, 'code_url': None, 'conference_name': 'WWW 2023'}, {'title': 'HGWaveNet: A Hyperbolic Graph Neural Network for Temporal Link Prediction', 'authors': 'Qijie Bai, Changli Nie, Haiwei Zhang, Dongming Zhao, Xiaojie Yuan', 'pdf_link': None, 'code_url': None, 'conference_name': 'WWW 2023'}, {'title': 'Rethinking Structural Encodings: Adaptive Graph Transformer for Node Classification Task', 'authors': 'Xiaojun Ma, Qin Chen, Yi Wu, Guojie Song, Liang Wang, Bo Zheng', 'pdf_link': None, 'code_url': None, 'conference_name': 'WWW 2023'}, {'title': 'CMINet: a Graph Learning Framework for Content-aware Multi-channel Influence Diffusion', 'authors': 'Hsi-Wen Chen, De-Nian Yang, Wang-Chien Lee, Philip S. Yu, Ming-Syan Chen', 'pdf_link': None, 'code_url': None, 'conference_name': 'WWW 2023'}, {'title': 'Federated Node Classification over Graphs with Latent Link-type Heterogeneity', 'authors': 'Han Xie, Li Xiong, Carl Yang', 'pdf_link': None, 'code_url': None, 'conference_name': 'WWW 2023'}, {'title': 'Expressive and Efficient Representation Learning for Ranking Links in Temporal Graphs', 'authors': 'Susheel Suresh, Mayank Shrivastava, Arko Mukherjee, Jennifer Neville, Pan Li', 'pdf_link': None, 'code_url': None, 'conference_name': 'WWW 2023'}, {'title': 'Semi-Supervised Embedding of Attributed Multiplex Networks', 'authors': 'Ylli Sadikaj, Justus Rass, Yllka Velaj, Claudia Plant', 'pdf_link': None, 'code_url': None, 'conference_name': 'WWW 2023'}, {'title': 'Search to Capture Long-range Dependency with Stacking GNNs for Graph Classification', 'authors': 'Lanning Wei, Zhiqiang He, Huan Zhao, Quanming Yao', 'pdf_link': None, 'code_url': None, 'conference_name': 'WWW 2023'}, {'title': 'HINormer: Representation Learning On Heterogeneous Information Networks with Graph Transformer', 'authors': 'Qiheng Mao, Zemin Liu, Chenghao Liu, Jianling Sun', 'pdf_link': None, 'code_url': None, 'conference_name': 'WWW 2023'}, {'title': 'Auto-HeG: Automated Graph Neural Network on Heterophilic Graphs', 'authors': 'Xin Zheng, Miao Zhang, Chunyang Chen, Qin Zhang, Chuan Zhou, Shirui Pan', 'pdf_link': None, 'code_url': None, 'conference_name': 'WWW 2023'}, {'title': 'Generating Counterfactual Hard Negative Samples for Graph Contrastive Learning', 'authors': 'Haoran Yang, Hongxu Chen, Sixiao Zhang, Xiangguo Sun, Qian Li, Xiangyu Zhao, Guandong Xu', 'pdf_link': None, 'code_url': None, 'conference_name': 'WWW 2023'}, {'title': 'Minimum Topology Attacks for Graph Neural Networks', 'authors': 'Mengmei Zhang, Xiao Wang, Chuan Shi, Lingjuan Lyu, Tianchi Yang, Junping Du', 'pdf_link': None, 'code_url': None, 'conference_name': 'WWW 2023'}, {'title': 'Multi-head Variational Graph Autoencoder Constrained by Sum-product Networks', 'authors': 'Riting Xia, Yan Zhang, Chunxu Zhang, Xueyan Liu, Bo Yang', 'pdf_link': None, 'code_url': None, 'conference_name': 'WWW 2023'}, {'title': 'GIF: A General Graph Unlearning Strategy via Influence Function', 'authors': 'Jiancan Wu, Yi Yang, Yuchun Qian, Yongduo Sui, Xiang Wang, Xiangnan He', 'pdf_link': None, 'code_url': None, 'conference_name': 'WWW 2023'}, {'title': 'Learning Mixtures of Markov Chains with Quality Guarantees', 'authors': 'Fabian Spaeh, Charalampos Tsourakakis', 'pdf_link': None, 'code_url': None, 'conference_name': 'WWW 2023'}, {'title': 'INCREASE: Inductive Graph Representation Learning for Spatio-Temporal Kriging', 'authors': 'Chuanpan Zheng, Xiaoliang Fan, Cheng Wang, Jianzhong Qi, Chaochao Chen, Longbiao Chen', 'pdf_link': None, 'code_url': None, 'conference_name': 'WWW 2023'}, {'title': 'Dual Intent Enhanced Graph Neural Network for Session-based New Item Recommendation', 'authors': 'Di Jin, Luzhi Wang, Yizhen Zheng, Guojie Song, Fei Jiang, Xiang Li, Wei Lin, Shirui Pan', 'pdf_link': None, 'code_url': None, 'conference_name': 'WWW 2023'}, {'title': 'Cut-matching Games for Generalized Hypergraph Ratio Cuts', 'authors': 'Nate Veldt', 'pdf_link': None, 'code_url': None, 'conference_name': 'WWW 2023'}, {'title': 'Toward Degree Bias in Embedding-Based Knowledge Graph Completion', 'authors': 'Harry Shomer, Wei Jin, Wentao Wang, Jiliang Tang', 'pdf_link': None, 'code_url': None, 'conference_name': 'WWW 2023'}, {'title': 'Unlearning Graph Classifiers with Limited Data Resources', 'authors': 'Chao Pan, Eli Chien, Olgica Milenkovic', 'pdf_link': None, 'code_url': None, 'conference_name': 'WWW 2023'}, {'title': 'KGTrust: Evaluating Trustworthiness of SIoT via Knowledge Enhanced Graph Neural Networks', 'authors': 'Zhizhi Yu, Di Jin, Cuiying Huo, Zhiqiang Wang, Xiulong Liu, Heng Qi, Jia Wu, Lingfei Wu', 'pdf_link': None, 'code_url': None, 'conference_name': 'WWW 2023'}, {'title': 'GraphMAE2: A Decoding-Enhanced Masked Self-Supervised Graph Learner', 'authors': 'Zhenyu Hou, Yufei He, Yukuo Cen, Xiao Liu, Yuxiao Dong, Evgeny Kharlamov, Jie Tang', 'pdf_link': None, 'code_url': None, 'conference_name': 'WWW 2023'}, {'title': 'CogDL: A Comprehensive Library for Graph Deep Learning', 'authors': 'Yukuo Cen, Zhenyu Hou, Yan Wang, Qibin Chen, Yizhen Luo, Zhongming Yu, Hengrui Zhang, Xingcheng Yao, Aohan Zeng, Shiguang Guo, Yuxiao Dong, Yang Yang, Peng Zhang, Guohao Dai, Yu Wang, Chang Zhou, Hongxia Yang, Jie Tang', 'pdf_link': None, 'code_url': None, 'conference_name': 'WWW 2023'}, {'title': 'ApeGNN: Node-Wise Adaptive Aggregation in GNNs for Recommendation', 'authors': 'Dan Zhang, Yifan Zhu, Yuxiao Dong, Yuandong Wang, Wenzheng Feng, Evgeny Kharlamov, Jie Tang', 'pdf_link': None, 'code_url': None, 'conference_name': 'WWW 2023'}, {'title': 'Enhancing User Personalization in Conversational Recommenders', 'authors': 'Allen Lin, Ziwei Zhu, Jianling Wang, James Caverlee', 'pdf_link': None, 'code_url': None, 'conference_name': 'WWW 2023'}, {'title': 'LINet: A Location and Intention-Aware Neural Network for Hotel Group Recommendation', 'authors': 'Ruitao Zhu, Detao Lv, Yao Yu, Ruihao Zhu, Zhenzhe Zheng, Ke Bu, Quan Lu, Fan Wu', 'pdf_link': None, 'code_url': None, 'conference_name': 'WWW 2023'}, {'title': 'Multi-Modal Self-Supervised Learning for Recommendation', 'authors': 'Wei Wei, Chao Huang, Lianghao Xia, Chuxu Zhang', 'pdf_link': None, 'code_url': None, 'conference_name': 'WWW 2023'}, {'title': 'Distillation from Heterogeneous Models for Top-K Recommendation', 'authors': 'SeongKu Kang, Wonbin Kweon, Dongha Lee, Jianxun Lian, Xing Xie, Hwanjo Yu', 'pdf_link': None, 'code_url': None, 'conference_name': 'WWW 2023'}, {'title': 'On the Theories Behind Hard Negative Sampling for Recommendation', 'authors': 'Wentao Shi, Jiawei Chen, Fuli Feng, Jizhi Zhang, Junkang Wu, Chongming Gao, Xiangnan He', 'pdf_link': None, 'code_url': None, 'conference_name': 'WWW 2023'}, {'title': 'Fine-tuning Partition-aware Item Similarities for Efficient and Scalable Recommendation', 'authors': 'Tianjun Wei, Jianghong Ma, Tommy W. S. Chow', 'pdf_link': None, 'code_url': None, 'conference_name': 'WWW 2023'}, {'title': 'Exploration and Regularization of the Latent Action Space in Recommendation', 'authors': 'Shuchang Liu, Qingpeng Cai, Bowen Sun, Yuhao Wang, Ji Jiang, Dong Zheng, Peng Jiang, Kun Gai, Xiangyu Zhao, Yongfeng Zhang', 'pdf_link': None, 'code_url': None, 'conference_name': 'WWW 2023'}, {'title': 'Bootstrap Latent Representations for Multi-modal Recommendation', 'authors': 'Xin Zhou, Hongyu Zhou, Yong Liu, Zhiwei Zeng, Chunyan Miao, Pengwei Wang, Yuan You, Feijun Jiang', 'pdf_link': None, 'code_url': None, 'conference_name': 'WWW 2023'}, {'title': 'Tracing Knowledge Instead of Patterns: Stable Knowledge Tracing with Diagnostic Transformer', 'authors': 'Yu Yin, Le Dai, Zhenya Huang, Shuanghong Shen, Fei Wang, Qi Liu, Enhong Chen, Xin Li', 'pdf_link': None, 'code_url': None, 'conference_name': 'WWW 

In [58]:
df_papers = pd.DataFrame(papers) 
df_papers.head(30)

,title,authors,pdf_link,code_url,conference_name
0,Using diversity as a source of scientific inno...,Barbara Poblete,None,None,WWW 2023
1,Decolonizing Creative Labor in the age of AI,Payal Arora,None,None,WWW 2023
2,Concept Regulation in the Social Sciences,Zachary Elkins,None,None,WWW 2023
3,GNNs and Graph Generative models for biomedica...,Michalis Vazirgiannis,None,None,WWW 2023
4,CONNECTIVITY,Robert Melancton Metcalfe,None,None,WWW 2023
5,GELTOR: A Graph Embedding Method based on List...,"Masoud Reyhani Hamedani, Jin-Su Ryu, Sang-Wook...",None,None,WWW 2023
6,Graph-less Collaborative Filtering,"Lianghao Xia, Chao Huang, Jiao Shi, Yong Xu",None,None,WWW 2023
7,Fair Graph Representation Learning via Diverse...,"Zheyuan Liu, Chunhui Zhang, Yijun Tian, Erchi ...",None,None,WWW 2023
8,Multi-Aspect Heterogeneous Graph Augmentation,"Yuchen Zhou, Yanan Cao, Yongchao Liu, Yanmin S...",None,None,WWW 2023
9,Testing Cluster Properties of Signed Graphs,"Florian Adriaens, Simon Apers",None,None,WWW 2023
10,RSGNN: A Model-agnostic Approach for Enhancing...,"Zeyu Zhang, Jiamou Liu, Xianda Zheng, Yifei Wa...",None,None,WWW 2023
11,NeuKron: Constant-Size Lossy Compression of Sp...,"Taehyung Kwon, Jihoon Ko, Jinhong Jung, Kijung...",None,None,WWW 2023
12,Multi-aspect Diffusion Network Inference,"Hao Huang, Keqi Han, Beicheng Xu, Ting Gan",None,None,WWW 2023
13,Collaboration-Aware Graph Convolutional Networ...,"Yu Wang, Yuying Zhao, Yi Zhang, Tyler Derr",None,None,WWW 2023
14,Pairwise-interactions-based Bayesian Inference...,"Chao Gao, Yuchen Wang, Zhen Wang, Xianghua Li,...",None,None,WWW 2023
15,Encoding Node Diffusion Competence and Role Si...,"Jiazheng Zhang, Bang Wang",None,None,WWW 2023
16,Hierarchical Knowledge Graph Learning Enabled ...,"Zhilun Zhou, Yu Liu, Jingtao Ding, Depeng Jin,...",None,None,WWW 2023
17,Opinion Maximization in Social Networks via Le...,"Xiaotian Zhou, Zhongzhi Zhang",None,None,WWW 2023
18,SeeGera: Self-supervised Semi-implicit Graph V...,"Xiang Li, Tiandi Ye, Caihua Shan, Dongsheng Li...",None,None,WWW 2023
19,Graph Self-supervised Learning with Augmentati...,"Dong Chen, Xiang Zhao, Wei Wang, Zhen Tan, Wei...",None,None,WWW 2023
20,Enhancing Hierarchy-Aware Graph Networks with ...,"Jiajie Su, Chaochao Chen, Weiming Liu, Fei Wu,...",None,None,WWW 2023
21,Unifying and Improving Graph Convolutional Neu...,"Liangtian Wan, Xiaona Li, Huijin Han, Xiaoran ...",None,None,WWW 2023
22,HyConvE: A Novel Embedding Model for Knowledge...,"Chenxu Wang, Xin Wang, Zhao Li, Zirui Chen, Ji...",None,None,WWW 2023
23,Efficient Approximation Algorithms for the Dia...,"Ke Zhang, Xiaoqing Wang, Gong Cheng",None,None,WWW 2023
24,Neighborhood Structure Configuration Models,"Felix I. Stamm, Michael Scholkemper, Markus St...",None,None,WWW 2023
25,CurvDrop: A Ricci Curvature Based Approach to ...,"Yang Liu, Chuan Zhou, Shirui Pan, Jia Wu, Zhao...",None,None,WWW 2023
26,Disentangling Degree-related Biases and Intere...,"Hyunsik Yoo, Yeon-Chang Lee, Kijung Shin, Sang...",None,None,WWW 2023
27,ConsRec: Learning Consensus Behind Interaction...,"Xixi Wu, Yun Xiong, Yao Zhang, Yizhu Jiao, Jia...",None,None,WWW 2023
28,A Post-Training Framework for Improving Hetero...,"Cheng Yang, Xumeng Gong, Chuan Shi, Philip Yu",None,None,WWW 2023
29,Link Prediction on Latent Heterogeneous Graphs,"Trung-Kien Nguyen, Zemin Liu, Yuan Fang",None,None,WWW 2023

In [62]:
save_to_database(df_papers, conference_name= 'WWW 2023',DB_PATH=DB_PATH)

407개의 논문이 WWW 2023에 저장되었습니다.

# 2022 Accepted Papers

In [63]:
url="https://www.sigweb.org/toc/www22.html"
DB_PATH = 'www_conference_2022.db' 
create_database(DB_PATH)

Conference 테이블이 생성되었습니다.

In [64]:
def get_www_papers(page_link, conference_name):
    """WWW 2022 학회의 Accepted Papers 페이지에서 논문 정보 크롤링"""
    
    # 웹페이지 요청
    response = requests.get(page_link)
    
    if response.status_code != 200:
        print("❌ 페이지를 불러오지 못했습니다.")
        return []

    soup = BeautifulSoup(response.text, "html.parser")

    # HTML을 저장 (디버깅용)
    with open("www2022_accepted_papers.html", "w", encoding="utf-8") as f:
        f.write(soup.prettify())

    papers = []

    # 논문 제목과 저자 정보 추출
    for paper_section in soup.find_all("h3"):  # 논문 제목이 포함된 태그 찾기
        title_tag = paper_section.find("a")  # 제목이 포함된 a 태그 찾기
        author_list = paper_section.find_next_sibling("ul")  # 저자 목록이 포함된 ul 태그 찾기

        if title_tag and author_list:
            title_text = title_tag.text.strip()  # 제목 텍스트 추출
            authors = [li.text.strip() for li in author_list.find_all("li")]  # 저자 목록 추출
            author_text = ", ".join(authors)  # 저자 이름을 쉼표로 구분

            papers.append({
                "title": title_text,
                "authors": author_text,
                "pdf_link": None,
                "code_url": None,
                "conference_name": conference_name
            })

    return papers

In [65]:
papers = get_www_papers(url, 'WWW 2022')

In [66]:
df_papers = pd.DataFrame(papers) 
df_papers.head(5)

,title,authors,pdf_link,code_url,conference_name
0,WISE: Wavelet based Interpretable Stock Embedd...,"Mengying Zhu, Yan Wang, Fei Wu, Mengyuan Yang,...",None,None,WWW 2022
1,Cyclic Arbitrage in Decentralized Exchanges,"Ye Wang, Yan Chen, Haotian Wu, Liyi Zhou, Shui...",None,None,WWW 2022
2,An Exploratory Study of Stock Price Movements ...,"Sourav Medya, Mohammad Rasoolinejad, Yang Yang...",None,None,WWW 2022
3,DC-GNN: Decoupled Graph Neural Networks for Im...,"Chenchen Feng, Yu He, Shiyang Wen, Guojun Liu,...",None,None,WWW 2022
4,Multilingual Semantic Sourcing using Product I...,"Sourab Mangrulkar, Ankith M S, Vivek Sembium",None,None,WWW 2022

In [67]:
save_to_database(df_papers, conference_name= 'WWW 2022',DB_PATH=DB_PATH)

225개의 논문이 WWW 2022에 저장되었습니다.

# 2021 Accepted Papers

In [71]:
import requests
from bs4 import BeautifulSoup
import pandas as pd
import re

def get_www_papers(page_link, conference_name):
    """WWW 2021 학회의 Accepted Papers 페이지에서 논문 정보 크롤링 후 DataFrame 반환"""
    
    # 웹페이지 요청
    response = requests.get(page_link)
    
    if response.status_code != 200:
        print("❌ 페이지를 불러오지 못했습니다.")
        return pd.DataFrame()  # 빈 DataFrame 반환

    soup = BeautifulSoup(response.text, "html.parser")

    # HTML 저장 (디버깅용)
    with open("www2021_accepted_papers.html", "w", encoding="utf-8") as f:
        f.write(soup.prettify())

    papers = []

    # 논문 제목과 저자 정보 추출
    for row in soup.find_all("tr"):  # 각 논문이 포함된 행
        cells = row.find_all("td")

        if len(cells) >= 2:
            title_tag = cells[0].find("strong", style=lambda x: x and "color: #359c8d" in x)  # 논문 제목
            author_tag = cells[1]  # 저자 정보

            if title_tag and author_tag:
                title_text = title_tag.text.strip()

                # 저자 정보에서 "Authors:" 부분 제거 및 괄호 안의 대학/기관 정보 제거
                authors_raw = author_tag.text.replace("Authors:", "").strip()
                authors_cleaned = re.sub(r"\(.*?\)", "", authors_raw).strip()

                papers.append({
                    "title": title_text,
                    "authors": authors_cleaned,
                    "pdf_link": None,
                    "code_url": None,
                    "conference_name": conference_name
                })

    # DataFrame으로 변환
    df_papers = pd.DataFrame(papers)
    return df_papers

In [72]:
# 웹페이지 URL 및 데이터베이스 설정
url = "https://archives.iw3c2.org/www2021/program/papers/"
DB_PATH = "www_conference_2021.db"

# 데이터베이스 생성
create_database(DB_PATH)

# 논문 데이터 크롤링
df_papers = get_www_papers(url, "WWW 2021")

# 크롤링된 논문 데이터 확인
df_papers.head()

Conference 테이블이 생성되었습니다.

,title,authors,pdf_link,code_url,conference_name
0,“Is it a Qoincidence?”: An Exploratory Study o...,"Antonis Papasavva , Jeremy Blackburn , Gianluc...",None,None,WWW 2021
1,“Short is the Road that Leads from Fear to Hat...,"Punyajoy Saha , Binny Mathew , Pawan Goyal , K...",None,None,WWW 2021
2,"âGo eat a bat, Chang!â: On the Emergence o...","Fatemeh Tahmasbi , Leonard Schild , Chen Ling ...",None,None,WWW 2021
3,#Twiti: Social Listening for Threat Intelligence,"Hyejin Shin , Woochul Shim , Saebom Kim , Sol ...",None,None,WWW 2021
4,A Cooperative Memory Network for Personalized ...,"Jiahuan Pei , Pengjie Ren and Maarten de Rijke .",None,None,WWW 2021

In [73]:
save_to_database(df_papers, conference_name= 'WWW 2021',DB_PATH=DB_PATH)

355개의 논문이 WWW 2021에 저장되었습니다.

# 2020 Accepted Papers

In [87]:
import pandas as pd
import re
from bs4 import BeautifulSoup

def get_www_papers(html_file_path, conference_name):
    """저장된 HTML 파일에서 WWW 학회의 Accepted Papers 정보를 크롤링 후 DataFrame 반환"""

    # HTML 파일 읽기
    with open(html_file_path, "r", encoding="utf-8") as file:
        soup = BeautifulSoup(file, "html.parser")

    papers = []

    # 논문 제목, 저자, PDF 링크 추출
    for article in soup.find_all("div", class_="issue-item__content"):
        title_tag = article.find("h5", class_="issue-item__title")
        authors_tag = article.find("ul", {"aria-label": "authors"})
        pdf_link_tag = article.find("a", {"aria-label": "PDF"})  # PDF 링크 찾기

        if title_tag and authors_tag:
            title_text = title_tag.text.strip()

            # 저자 정보에서 괄호 속 대학/기관 제거
            authors_raw = ", ".join([a.text.strip() for a in authors_tag.find_all("span")])
            authors_cleaned = re.sub(r"\(.*?\)", "", authors_raw).strip()

            # PDF 링크 정리
            pdf_link = pdf_link_tag["href"] if pdf_link_tag else None

            papers.append({
                "title": title_text,
                "authors": authors_cleaned,
                "pdf_link": pdf_link,
                "code_url": None,
                "conference_name": conference_name
            })

    # DataFrame으로 변환
    df_papers = pd.DataFrame(papers)
    return df_papers

In [82]:
url = "https://dl.acm.org/doi/proceedings/10.1145/3366423#heading1"
DB_PATH = "www_conference_2020.db"

In [83]:
create_database(DB_PATH)

Conference 테이블이 생성되었습니다.

In [88]:
df_papers = get_www_papers("/home/cvlab/papers-update/conference/html/www2020_accepted_papers.html", "WWW 2020")

In [89]:
df_papers.head()

,title,authors,pdf_link,code_url,conference_name
0,Relation Adversarial Network for Low Resource ...,"Ningyu Zhang, ,, Shumin Deng, ,, Zhanlin Sun, ...",https://dl.acm.org/doi/pdf/10.1145/3366423.338...,None,WWW 2020
1,Learning to Classify: A Flow-Based Relation Ne...,"Wenbo Zheng, ,, Chao Gou, ,, Lan Yan, ,, Shaoc...",https://dl.acm.org/doi/pdf/10.1145/3366423.338...,None,WWW 2020
2,FiDo: Ubiquitous Fine-Grained WiFi-based Local...,"Xi Chen, ,, Hang Li, ,, Chenyi Zhou, ,, Xue Li...",https://dl.acm.org/doi/pdf/10.1145/3366423.338...,None,WWW 2020
3,An Empirical Study of the Use of Integrity Ver...,"Bertil Chapuis, ,, Olamide Omolola, ,, Mauro C...",https://dl.acm.org/doi/pdf/10.1145/3366423.338...,None,WWW 2020
4,Power-Law Graphs Have Minimal Scaling of Kemen...,"Wanyue Xu, ,, Yibin Sheng, ,, Zuobai Zhang, ,,...",https://dl.acm.org/doi/pdf/10.1145/3366423.338...,None,WWW 2020

In [90]:
save_to_database(df_papers, conference_name= 'WWW 2020',DB_PATH=DB_PATH)

219개의 논문이 WWW 2020에 저장되었습니다.

# 2019 Accepted Papers

In [115]:
import pandas as pd
import re
import requests
from bs4 import BeautifulSoup

def get_www_papers(page_link, conference_name):
    """WWW 학회의 Accepted Papers 페이지에서 논문 정보 크롤링 후 DataFrame 반환"""

    # 웹페이지 요청
    response = requests.get(page_link)
    
    if response.status_code != 200:
        print("❌ 페이지를 불러오지 못했습니다.")
        return pd.DataFrame()  # 빈 DataFrame 반환

    soup = BeautifulSoup(response.text, "html.parser")

    # HTML 저장 (디버깅용)
    with open("www2018_accepted_papers.html", "w", encoding="utf-8") as f:
        f.write(soup.prettify())

    papers = []

    # 논문 제목과 저자, PDF 링크, Code URL 추출
    for article in soup.find_all("div", class_="issue-item-container"):
        title_tag = article.find("h5", class_="issue-item__title")
        authors_tag = article.find("ul", {"aria-label": "authors"})
        pdf_link_tag = article.find("a", {"aria-label": "PDF"})  # PDF 링크 찾기
        code_link_tag = article.find("a", text="GitHub")  # 코드 URL (GitHub 링크)

        if title_tag and authors_tag:
            title_text = title_tag.text.strip()

            # 저자 정보에서 괄호 속 대학/기관 제거
            authors_raw = ", ".join([a.text.strip() for a in authors_tag.find_all("span")])
            authors_cleaned = re.sub(r"\(.*?\)", "", authors_raw).strip()

            # PDF 링크 정리
            pdf_link = pdf_link_tag["href"] if pdf_link_tag else None
            code_url = code_link_tag["href"] if code_link_tag else None  # 코드 URL 추출

            papers.append({
                "title": title_text,
                "authors": authors_cleaned,
                "pdf_link": pdf_link,
                "code_url": code_url,
                "conference_name": conference_name
            })

    # DataFrame으로 변환
    df_papers = pd.DataFrame(papers)
    return df_papers

In [119]:
DB_PATH = "www_conference_2018.db"
create_database(DB_PATH)

Conference 테이블이 생성되었습니다.

In [120]:
page_link = "https://dl.acm.org/doi/proceedings/10.5555/3178876"
conference_name = "WWW 2018"

df_papers = get_www_papers(page_link, conference_name)

# 데이터 확인
df_papers.head()

❌ 페이지를 불러오지 못했습니다.

Empty DataFrame
Columns: []
Index: []

In [100]:
save_to_database(df_papers,conference_name=conference_name, DB_PATH=DB_PATH)

360개의 논문이 WWW 2019에 저장되었습니다.

# KDD 2015

In [2]:
import sqlite3
import requests
from bs4 import BeautifulSoup
import pandas as pd

def create_database(DB_PATH):
    """Create the database and the Conference table."""
    conn = sqlite3.connect(DB_PATH)
    cursor = conn.cursor()

    cursor.execute('''
    CREATE TABLE IF NOT EXISTS Conference (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        Title TEXT NOT NULL,
        Author TEXT NOT NULL,
        PDF_Link TEXT,
        Code_URL TEXT,
        Conference_Name TEXT NOT NULL
    )
    ''')

    print("Conference 테이블이 생성되었습니다.")
    conn.commit()
    conn.close()

def save_to_database(df, conference_name, DB_PATH):
    conn = sqlite3.connect(DB_PATH, timeout=10)
    cursor = conn.cursor()

    try:
        for _, row in df.iterrows():  # ✅ iterrows() 사용하여 DataFrame의 각 행을 처리
            # 중복 데이터 확인
            cursor.execute('''
            SELECT 1 FROM Conference WHERE Title = ? AND Author = ? AND Conference_Name = ?
            ''', (row['title'], row['authors'], conference_name))
            result = cursor.fetchone()

            if not result:
                cursor.execute('''
                INSERT INTO Conference (Title, Author, PDF_Link, Code_URL, Conference_Name)
                VALUES (?, ?, ?, ?, ?)
                ''', (row['title'], row['authors'], row['pdf_link'], row['code_url'], conference_name))

        conn.commit()
        print(f"{len(df)}개의 논문이 {conference_name}에 저장되었습니다.")
    except sqlite3.Error as e:
        print(f"Database error: {e}")
    finally:
        conn.close()

In [3]:
url = 'https://dblp.org/db/conf/kdd/kdd2015.html'
DB_PATH = "con_db/KDD_conference_2015.db"
conference_name = 'KDD 2015'
create_database(DB_PATH)

Conference 테이블이 생성되었습니다.

In [4]:
response = requests.get(url) 
soup =BeautifulSoup(response.text, 'html.parser')
with open('html/KDD_2015_accepted_papers.html', 'w', encoding='utf-8') as f:
    f.write(soup.prettify())

In [20]:
def get_www_papers(html_file_path, conference_name):
    """저장된 HTML 파일에서 KDD 학회의 Accepted Papers 정보를 크롤링 후 DataFrame 반환"""

    # HTML 파일 읽기
    with open(html_file_path, "r", encoding="utf-8") as file:
        soup = BeautifulSoup(file, "html.parser")

    papers = []

    # 논문 리스트가 포함된 섹션 찾기
    for entry in soup.find_all("li", class_="entry inproceedings"):
        # 제목 찾기
        title_tag = entry.find("span", class_="title")
        title_text = title_tag.text.strip() if title_tag else "Unknown"

        # 저자 찾기
        authors_tags = entry.find_all("span", itemprop="author")
        authors_list = [author.find("span", itemprop="name").text.strip() for author in authors_tags]
        authors_cleaned = ", ".join(authors_list)

        # PDF 링크 찾기
        pdf_tag = entry.find("a", href=re.compile(r"doi\.org"))
        pdf_link = pdf_tag["href"] if pdf_tag else None

        # 논문 정보 추가
        papers.append({
            "title": title_text,
            "authors": authors_cleaned,
            "pdf_link": pdf_link,
            "code_url": None,
            "conference_name": conference_name
        })

    # DataFrame으로 변환
    df_papers = pd.DataFrame(papers)
    return df_papers

In [21]:
df_papers = get_www_papers('html/KDD_2015_accepted_papers.html',conference_name)

In [22]:
df_papers.head()

,title,authors,pdf_link,code_url,conference_name
0,Online Controlled Experiments: Lessons from Ru...,Ron Kohavi,https://doi.org/10.1145/2783258.2785464,None,KDD 2015
1,MOOCS: What Have We Learned?,Daphne Koller,https://doi.org/10.1145/2783258.2785465,None,KDD 2015
2,Machine Learning and Causal Inference for Poli...,Susan Athey,https://doi.org/10.1145/2783258.2785466,None,KDD 2015
3,"Data, Knowledge and Discovery: Machine Learnin...",Hugh F. Durrant-Whyte,https://doi.org/10.1145/2783258.2785467,None,KDD 2015
4,Large-Scale Distributed Bayesian Matrix Factor...,"Sungjin Ahn, Anoop Korattikara, Nathan Liu, Su...",https://doi.org/10.1145/2783258.2783373,None,KDD 2015

In [23]:
df_papers = df_papers.drop(index=[0,1,2,3])

In [24]:
df_papers.head()

,title,authors,pdf_link,code_url,conference_name
4,Large-Scale Distributed Bayesian Matrix Factor...,"Sungjin Ahn, Anoop Korattikara, Nathan Liu, Su...",https://doi.org/10.1145/2783258.2783373,None,KDD 2015
5,TimeMachine: Timeline Generation for Knowledge...,"Tim Althoff, Xin Luna Dong, Kevin Murphy, Safa...",https://doi.org/10.1145/2783258.2783325,None,KDD 2015
6,Estimating Local Intrinsic Dimensionality.,"Laurent Amsaleg, Oussama Chelly, Teddy Furon, ...",https://doi.org/10.1145/2783258.2783405,None,KDD 2015
7,Portraying Collective Spatial Attention in Twi...,"Émilien Antoine, Adam Jatowt, Shoko Wakamiya, ...",https://doi.org/10.1145/2783258.2783418,None,KDD 2015
8,Accelerating Dynamic Time Warping Clustering w...,"Nurjahan Begum, Liudmila Ulanova, Jun Wang, Ea...",https://doi.org/10.1145/2783258.2783286,None,KDD 2015

In [25]:
df_papers.tail()

,title,authors,pdf_link,code_url,conference_name
248,VC-Dimension and Rademacher Averages: From Sta...,"Matteo Riondato, Eli Upfal",https://doi.org/10.1145/2783258.2789984,None,KDD 2015
249,Large Scale Distributed Data Science using Apa...,"James G. Shanahan, Liang Dai",https://doi.org/10.1145/2783258.2789993,None,KDD 2015
250,Medical Mining: KDD 2015 Tutorial.,"Myra Spiliopoulou, Pedro Pereira Rodrigues, Er...",https://doi.org/10.1145/2783258.2789992,None,KDD 2015
251,Big Data Analytics: Optimization and Randomiza...,"Tianbao Yang, Qihang Lin, Rong Jin",https://doi.org/10.1145/2783258.2789989,None,KDD 2015
252,Data Driven Science: SIGKDD Panel.,"Katharina Morik, Hugh F. Durrant-Whyte, Gary C...",https://doi.org/10.1145/2783258.2788703,None,KDD 2015

In [26]:
save_to_database(df_papers, conference_name, DB_PATH)

249개의 논문이 KDD 2015에 저장되었습니다.

# KDD 2014

In [27]:
url = 'https://dblp.org/db/conf/kdd/kdd2014.html'
DB_PATH = "con_db/KDD_conference_2014.db"
conference_name = 'KDD 2014'
create_database(DB_PATH)

Conference 테이블이 생성되었습니다.

In [28]:
response = requests.get(url) 
soup =BeautifulSoup(response.text, 'html.parser')
with open('html/KDD_2014_accepted_papers.html', 'w', encoding='utf-8') as f:
    f.write(soup.prettify())

In [29]:
df_papers = get_www_papers('html/KDD_2014_accepted_papers.html',conference_name)

In [30]:
df_papers.head()

,title,authors,pdf_link,code_url,conference_name
0,The battle for the future of data mining.,Oren Etzioni,https://doi.org/10.1145/2623330.2630816,None,KDD 2014
1,"Data, predictions, and decisions in support of...",Eric Horvitz,https://doi.org/10.1145/2623330.2630815,None,KDD 2014
2,A data driven approach to diagnosing and treat...,Eric E. Schadt,https://doi.org/10.1145/2623330.2630817,None,KDD 2014
3,Bugbears or legitimate threats?: (social) scie...,Sendhil Mullainathan,https://doi.org/10.1145/2623330.2630818,None,KDD 2014
4,Prediction of human emergency behavior and the...,"Xuan Song, Quanshi Zhang, Yoshihide Sekimoto, ...",https://doi.org/10.1145/2623330.2623628,None,KDD 2014

In [31]:
df_papers = df_papers.drop(index=[0,1,2,3])

In [32]:
df_papers.head()

,title,authors,pdf_link,code_url,conference_name
4,Prediction of human emergency behavior and the...,"Xuan Song, Quanshi Zhang, Yoshihide Sekimoto, ...",https://doi.org/10.1145/2623330.2623628,None,KDD 2014
5,Inferring user demographics and social strateg...,"Yuxiao Dong, Yang Yang, Jie Tang, Yang Yang, N...",https://doi.org/10.1145/2623330.2623703,None,KDD 2014
6,Travel time estimation of a path using sparse ...,"Yilun Wang, Yu Zheng, Yexiang Xue",https://doi.org/10.1145/2623330.2623656,None,KDD 2014
7,Modeling human location data with mixtures of ...,"Moshe Lichman, Padhraic Smyth",https://doi.org/10.1145/2623330.2623681,None,KDD 2014
8,A cost-effective recommender system for taxi d...,"Meng Qu, Hengshu Zhu, Junming Liu, Guannan Liu...",https://doi.org/10.1145/2623330.2623668,None,KDD 2014

In [33]:
save_to_database(df_papers, conference_name, DB_PATH)

216개의 논문이 KDD 2014에 저장되었습니다.